### ISSUE TITLE
Incompatibility with json_schema?

### ISSUE THREAD

**Issue by gjtorikian** [interagent/prmd#198]
I've been struggling to resolve an increasingly irritating problem with my JSON schema. I think the source of the issue might be from prmd; it deals with what appears to be some inconsistent handling of schemas, as compared to @brandur's [json_schema](https://github.com/brandur/json_schema) gem.

Let's say you have a *meta.json* like this:

``` json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema",
  "id": "schema.json",
  "properties": {
    "foof.json": {
      "$ref": "foof.json#"
    }
  },
  "type": [
    "object"
  ]
}
``` 

And, *foof.json* looks a little bit like this:

``` json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema",
  "id": "foof.json",
  "type": [
    "object"
  ],
  "definitions": {
    "body": {
      "description": "Contents of the foof",
      "example": "It looks like the new widget.",
      "type": [
        "string",
        "null"
      ]
    },
    "title": {
      "description": "Title of the foof",
      "example": "Widget creation",
      "type": "string"
    }
  },
  "links": [
    {
      "description": "Create a new foof.",
      "method": "POST",
      "rel": "create",
      "schema": {
        "properties": {
          "body": {
            "$ref": "#/definitions/body"
          },
          "title": {
            "$ref": "#/definitions/title"
          }
        },
        "required": [
          "title"
        ],
        "type": [
          "object"
        ]
      },
      "title": "Create"
    }
  ]
}
```

Using json_schema, I iterate over this subschema, and generate my final schema, basically as described [in this issue](https://github.com/brandur/json_schema/issues/22).

If I pass a data hash like this:

```
{
  body: { "not" => "valid"},
  title: "valid"
}
```

The validation fails, as it should: although `title` is provided, and a `string`, `body` is a `hash`, when it should be a `string`.

Cool. So everything works here!

The problem arrises when I run `prmd` to validate my schema:

```
prmd combine --meta meta.json schemas/ > final.json && prmd verify final.json 
```

It complains with:

```
final.json: #: Couldn't resolve pointer "#/definitions/definitions/body".
```

Digging into *final.json*, I find the problem: it seems that prmd has chosen to embed an extra `/definitions` path:
 ```              
"body": {
   "$ref": "#/definitions/definitions/body"
},
```

Now, I could rewrite the original path to become something like:

```
"#/foof.json/definitions/body"
```

Doing that makes prmd happy; but then, json_schema fails to validate! It accepts the faulty data hash. Digging into json_schema a bit, I find that the `schema` reference in the link is not expanded; that is, its `to_s` is marked as `[COLLAPSED] [original]`, which I take to mean, "I didn't even bother to resolve these `$ref`s.

Is there any way to write my schema to get these two pieces of software to play nicely?

I'm using prmd 0.7.0 and json_schema 0.4.0, if it helps.

**Comment by geemus** [comment]
I think it might be a misunderstanding mostly, but I'm not certain. prmd inserts the extra definitions, because it expects foof.json and others to live and a `schemata` directory and define individual resources. Combine will pull all of those together and make each subschema it's own definition (then list them individually as properties). So the extra definition there is intended, and usually works. You would be operating on the result of this `combine` call then, rather than using any of the individual schemas.

Does that help/makes sense at all? I've done similar things and had it work alright, so I'm not exactly sure where things are going off the rails. I'd be happy to discuss further, I think having a bit more detail around the directory structure and the specifics of the commands you are running could help me nail it down a bit more concretely. Thanks!

**Comment by gjtorikian** [comment]
I mean, I understand that I should operate on the `prmd` combination, rather than the individual resources. What I'm saying is that if I try to combine the individual schema resources using JsonSchema in my Ruby code, the data validations are successful; yet, when I try to combine the files from the command line, the extra definition insertion causes an error, without my changing of any `$ref`s or IDs. I wonder if I should just programmatically iterate using the PRMD classes in my Ruby code, rather than the JsonSchema Ruby code?

I guess I just don't get how my setup results in two different outputs from combining the schemas, you know? In theory, both validations should pass, because they both follow the spec. I can get the validation to pass for json_schema but fail for prmd, or I can tweak my `$ref`s to make the validation pass for prmd, but then it fails for json_schema.

**Comment by geemus** [comment]
Could you share the specific schemata and command line arguments you are using? I think that may be easier for me to look at and help with than talking more in the abstract. Thanks!

**Comment by gjtorikian** [comment]
@geemus Hah! Of course.

Here's a zip containing a test case: https://github.com/gjtorikian/testing/releases/tag/1.x

If you run `ruby combine.rb`, JSON schema slurps up the meta schema and the subschemas, and performs validations. The validations work--`body` is an object, when it should be a `string` or `null`.

But if you try to run `prmd combine --meta schema.json schemas > final.json && prmd verify final.json`, `prmd` errors out.

I can change the strings in `$ref` to make `prmd` happy. But if I do that, then JSON schema fails to validate correctly. (It performs a combination, but does not expand the `schema` of my links.) That's why I'm not sure where the problem lies: this gem, that gem, or me. :grinning:

**Comment by gjtorikian** [comment]
Any news on this, or can I help provide more info?

**Comment by geemus** [comment]
Sorry, just got a bit swamped by other stuff. I'll try to revisit in the next couple days though, sorry for the delay!

**Comment by geemus** [comment]
Ah ha. So first off, I would expect the subschema refs to look like: `/schemas/issue.json#/definitions/title`. That makes them be more globally accurate instead of only being correct relatively I believe. I made that change and combine.rb still worked fine.

prmd EXPLODED though, as you noted.

The reason is kind of silly, so I'll explain and give the easy and hard fixes.

We chose the alternate pluralization of schema for our tools, namely, schemata. There are presently a few things that are hard-coded to expect this, so they were not aware of how to deal with `schemas`, although that is also a valid pluralization. So...

Easier - You could change the pluralization to `schemata` and fix the references to use this. I think in this case it should just work for both tools.

Harder - We could change prmds combiner to realize this is a thing and look for either schemata or schemas when it does it's thing.

Does that help/make sense? Again, sorry it took me so long to circle back, it's been a crazy busy time.

**Comment by gjtorikian** [comment]
No worries! I understand busy schedules, believe me.

We ended up going a different route, and have just decided to rely on `prmd` for what we need to do. A `Prmd.combine` followed by `.verify` achieves what we need, so we'll just scope our schema to match that.

I appreciate you taking the time for describing the easy and hard resolutions!

I'll close this out as there's nothing really actionable here for you to do. :heart:

**Comment by gjtorikian** [comment]
In case anyone from The Future is curious, we're now doing something like:

``` ruby
schema = Prmd.combine(subschema_paths, :meta => meta_schema_path)
data = JSON.parse(schema.to_json)
errors = Prmd.verify(data)
fail(ParseError, errors) unless errors.empty?
JsonSchema.parse!(data)
```

**Comment by geemus** [comment]
Thanks for the update, glad to hear you got it working.

**Comment by panSarin** [comment]
Hey . I have similiar problem ( /definitions# prefix is the issue) , and not sure where i should find a solution - in PRMD or in JsonSchema.

I described my first problem there:

https://github.com/brandur/json_schema/issues/46

and json_schema solution for this issue is there:

https://github.com/brandur/json_schema/issues/22#issuecomment-65129746

But when i applied this solution in my final api.json file after combining i get something like

https://gist.github.com/panSarin/fab4bdc553c32891476a

So should i ask @brandur about how else can i make JsonSchema works with pointers, or maybe should i pass some options during combining ? Or maybe after combining i should implement some script that will remove #/definitions prefix ?;p 
Any ideas? @gjtorikian  maybe you have some experience in this area?

**Comment by geemus** [comment]
My inclination would be toward recommending you implement your own version of combine that does-the-right thing for your purposes. The patterns within prmd come from the expected use case, which it seems doesn't include your case. Once we have nailed down a better idea of how we can accomodate your case, I could certainly see working toward having this as options to combine, but figuring out the specifics in isolation seems likely to be easier/faster initially. Thanks!

**Comment by panSarin** [comment]
Thank you for so fast reply! I will paste my implementation there if i will manage to do it - maybe it will be helpfull for someone.

**Comment by geemus** [comment]
@panSarin sounds like a plan, thanks for working through it with us. Just let me know if you have questions.

**Comment by brandur** [comment]
Sorry to hear that this is turning into such a yakshave @panSarin! Let us know how it turns out.
