### ISSUE TITLE
Nullable nested objects?

### ISSUE THREAD

**Issue by bdmac** [interagent/prmd#255]
I'm unsure how to handle the case of an object that embeds another object via `$ref` when that other object can legitimately be `null` such that I can both generate docs using prmd **and** validate against my schema using the committee gem. As far as I can tell from json-schema docs I would need to do something like this fragment:
```
...
    "industry": {
      "description": "the business' industry",
      "anyOf": [
        { "$ref": "/schemata/industry" },
        { "type": "null"}
      ]      
    }
...
```
but this fails to validate against prmd's schema for documentation. If I just do
```
"industry": {
  "$ref": "/schemata/industry"
}
```
then the docs verify but a JSON response with `"industry": null` fails to pass against committee with a bunch of `nil is not an object.` errors.

Am I missing something obvious here?

**Comment by bdmac** [comment]
I was able to hack (at least it feels like a hack to me) around this by modifying the `industry.json` schemata's type to include "null" in the array. This feels a bit odd to do within the `industry` schemata/resource itself instead of doing this within the places that reference the industry.

**Comment by geemus** [comment]
I think that you could also have "$ref" like in your first example, but then also have `"type": ["object", "null"]` in that same place (rather than embeded inside the ref-ed schema). The behavior in that case is similar to ruby hash merges, so it would start with the ref-ed thing and then merge local attributes on top. I think that would give you what you want (while limiting the scope to which the null might apply). Does that make sense? I'm not certain the tooling will play nice with it, so we may still need to fix things, but it seems like the right thing technically/semantically within json-schema from my understanding. What do you think?

**Comment by bdmac** [comment]
Yep that makes sense. I found another thread asking something similar where you suggested that. I didn't realize ref merged that way from the spec.

**Comment by geemus** [comment]
@bdmac cool. I'm not sure I could point to where exactly it says that, but that is what I infer/understand from some of the examples and things.

**Comment by mcclymont** [comment]
@geemus in my application we declared nullable objects inside /definitions like the way @bdmac showed:

```
"app": {
  "description": "app of the user",
  "anyOf": [
    { "$ref": "/schemata/app#" },
    { "type": "null" }
  ]
}
```

It used to work. But after updating prmd to 0.8.0 I get this error:

```failed schema #/definitions/resource/dependencies/properties/definitions/additionalProperties: No subschema in "anyOf" matched.``` Our app with committee kept working as intended, but prmd would not verify and generate our docs.

I tried what you suggested, like this:

```
"app": {
  "description": "app of the user",
  "type": ["object", "null"],
  "$ref": "/schemata/app#"
}
```

and it passes through prmd, but doesn't work in committee. It says 

```{"id":"invalid_response","message":"Invalid response.\n\n#/app: failed schema #/definitions/user/properties/app: For 'properties/app', nil is not an object."}```

So it seems that in committee, it hasn't shows the "ruby hash merge" behaviour that you described in your coment. I.e. the app has type "object" but the local declaration of "type": ["object", "null"] should override that.

I have created a basic Rails repo to show this issue:
https://github.com/mcclymont/rails4-routing-example/tree/nullable-ref-issue

**Comment by geemus** [comment]
@mcclymont sorry for the delay, trying to pin this down. Could you try reversing the elements to `["null", "object"]`? It looks like we use it that way successfully, if I'm not mistaken. It seems like it should work both ways, but if we know it only works in the one order it can provide you a workaround in the mean time (and perhaps help point more specifically toward the actual issue as well). Thanks!

**Comment by mcclymont** [comment]
@geemus Tried reversing the types, that didn't change the response from committee.
https://github.com/mcclymont/rails4-routing-example/commit/1cc53f5f2c9a7c62e7386ffbfa710565ae9fc7d1

**Comment by geemus** [comment]
@brandur do you have any insight here? Thanks!

**Comment by brandur** [comment]
Hey guys! Sorry about the crazy delay in response here.

So just as a introductory question, @geemus are you sure that the merge behavior described above is correct? The [JSON reference draft](https://json-spec.readthedocs.org/en/latest/reference.html) is unfortunately a little vague, but the most relevant lines I can find are these:

>    Resolution of a JSON Reference object SHOULD yield the referenced
>   JSON value.  Implementations MAY choose to replace the reference with
>   the referenced value.

It's not definitive, but the wording around "replace" seems to suggest that the intent was simple replacement rather than any other behavior. Wes, if you want, I notice that one of the authors is still at SFDC. I might be worth dropping him an internal e-mail to see if we can get a less ambiguous answer on the subject.

So yes, it seems that if the merge behavior is correct, then this is a bug in the json_schema gem's reference resolver, which I'm happy to fix, but otherwise we might have to modify prmd a bit to handle the `anyOf` style which was described above:

``` json
"app": {
  "description": "app of the user",
  "anyOf": [
    { "$ref": "/schemata/app#" },
    { "type": "null" }
  ]
}
```

(Which looks valid to me.)

**Comment by geemus** [comment]
I am not sure, that had just been my understanding/assumption. Maybe we need prmd tweaks after all.

**Comment by geemus** [comment]
I probably don't have bandwidth to chase this down at the moment, but happy to support any such efforts if somebody wants to go for it.

**Comment by tsrivishnu** [comment]
This issue still exists. @brandur @bdmac Do you guys have a solution to this?
