### ISSUE TITLE
Dasherized attributes (json-api)

### ISSUE THREAD

**Issue by bdmac** [interagent/prmd#257]
The JSON API spec recommends dasherized keys for attribute and resource names. The PRMD custom schema does not appear to allow dashes. Is there a reason for this?

In schemas/interagent-hyper-schema.json:
```json
...
                  "properties": {
                    "patternProperties": {
                        "^[a-z][a-zA-Z_]*[a-zA-Z]$": {
                            "$ref": "#/definitions/resourceProperty"
                        }
                    },
                    "strictProperties": true
                },
...
```

**Comment by geemus** [comment]
Probably our preference and/or historical reasons. We happen to use underscore here because we always have, but I'm pretty sure it also makes them a bit easier to access from JavaScript (or at least that was the case, once upon a time). I don't think there is any particular reason we couldn't loosen this though, would you be up for a PR to that effect? Thanks!

**Comment by bdmac** [comment]
Sure I've already got it modified on our fork so we can use prmd. Will push upstream later today.

**Comment by geemus** [comment]
Sounds good, thanks! I'll close this before I forget, but look forward to the fix.
