### ISSUE TITLE
Generating documentation for non-JSON API routes

### ISSUE THREAD

**Issue by CheshireSwift** [interagent/prmd#351]
Our API consists mostly of JSON responses, documented via a schema fed through prmd. A handful of routes are redirections (e.g. to S3 buckets for assets). Am I right in my assessment that prmd doesn't offer any way of documenting routes that do anything other than return JSON objects?

Is there any suggestion for a more convenient option than editing the generated markdown manually/writing our own automation to postprocess prmd's output?

**Comment by geemus** [comment]
I don't think we happened to have use cases that didn't have json responses (such as the redirections you mention), so it may not have come up. I don't know of a more convenient option off hand, though I must also admit it's been quite some time since I've worked on/around this stuff due to job changes. We could discuss changes to support this otherwise, but I suspect post processing of some sort is probably going to be the quickest and easiest fix at this time.

**Comment by CheshireSwift** [comment]
Gotcha, thanks 🙏
