### ISSUE TITLE
unable to use type as property/definition

### ISSUE THREAD

**Issue by progrium** [interagent/prmd#53]
I don't believe there are reserved words for JSON schema but `prmd doc` barfs when I have a schema that has a property/definition with the name `type`.

**Comment by incorvia** [comment]
Unsure if this is the same issue but I have a property "type" in my definition that is of type "String" that I don't want converted to an array. Since convert_type_to_array converts performs:

      when Hash
        if datum.key?('type') && datum['type'].is_a?(String)
          datum['type'] = [*datum['type']]
        end
        datum.each_with_object({}) do |(k, v), hash|
          hash[k] = convert_type_to_array(v)
        end
      else
        datum
      end

It means that if I have a key of "type" in an "example" it will change my example. For example in a definition with an example of:

 "example": [ { "type": "test" } ]

Will get converted to: 

     "example": [ { "type": ["test"] } ]

... when the combiner runs. One solution would be additional check could be applied to ensure that we don't modify examples. There seems to be a number of tickets around this whole "type => array" thing so maybe something else needs to be thought through?

**Comment by geemus** [comment]
@incorvia thanks for the details. It was meant to be a simplifying assumption (ie, it makes it a bit easier to process/work with if you can assume type is an array). It seems 1) unexpected and 2) hard to ensure it only happens in particular narrow contexts. So my vote would be to just stop doing this altogether, would you be up for a PR in that direction? Removing the modification would be a great place to start, though I suspect there may be parts of the documentation generation that will also need tweaked to accommodate type possible being a single value. What do you think?
